// Public, indexable documents only; component templates and editor payloads are not pages.
export const origin = 'https://cocoonframework.com';
export const pages = [
  ['index.html', '/', 'Cocoon — Browser-native JavaScript components', 'Cocoon is a standards-first framework for native web applications with HTML, CSS and JavaScript, no virtual DOM and no mandatory build step.'],
  ['get-started.html', '/get-started.html', 'Get started — Cocoon', 'Build your first Cocoon component with HTML, CSS and JavaScript. Follow the runnable od-cocoon quickstart.'],
  ['docs.html', '/docs.html', 'Framework reference — Cocoon', 'Explore the Cocoon framework reference: components, namespaces, imports, lifecycle, styles and application architecture.'],
  ['privacy.html', '/privacy.html', 'Privacy & cookies — Cocoon', 'How the Cocoon website uses browser storage and optional analytics, and how to contact its operator.'],
  ['getting-started/index.html', '/getting-started/index.html', 'Component to application — Cocoon', 'Explore runnable Cocoon examples, from your first native component to import maps and a complete application.'],
  ['showcase/index.html', '/showcase/index.html', 'Interactive component lab — Cocoon', 'Inspect Cocoon component structure, inherited styles and signals. Explore source code and edit runnable examples in the component lab.'],
  ['lifecycle/index.html', '/lifecycle/index.html', 'Component lifecycle — Cocoon', 'Follow a Cocoon component through discovery, definition, styling, rendering and connection in the interactive lifecycle lab.'],
  ['simulation/index.html', '/simulation/index.html', 'Flocking simulation — Cocoon', 'Explore Flocking Worlds, an interactive Cocoon simulation, and inspect or download its source code.'],
  ['parallel/index.html', '/parallel/index.html', 'Parallel compute benchmark — Cocoon', 'Explore multicore parallel computation with the interactive Cocoon Mandelbrot benchmark and its source code.'],
];
const escape = value => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
export function metadata(file) {
  const page = pages.find(page => page[0] === file);
  if (!page) throw new Error(`Missing SEO entry: ${file}`);
  const [, path, title, description] = page;
  const url = origin + path;
  const graph = [{ '@type':'WebSite', '@id':origin + '/#website', url:origin + '/', name:'Cocoon' },
    { '@type':file === 'docs.html' || file === 'get-started.html' ? 'TechArticle' : 'WebPage', '@id':url + '#page', url, name:title, description, isPartOf:{ '@id':origin + '/#website' } }];
  if (file === 'index.html') graph.push({ '@type':'SoftwareSourceCode', '@id':origin + '/#software', name:'Cocoon', alternateName:'od-cocoon', url:origin + '/', description, codeRepository:'https://github.com/Nashorn/od-cocoon', programmingLanguage:'JavaScript' });
  return `<!-- SEO metadata: generated by scripts/seo.mjs -->
  <title>${escape(title)}</title>
  <meta name="description" content="${escape(description)}">
  <link rel="canonical" href="${url}">
  <meta property="og:type" content="website">
  <meta property="og:site_name" content="Cocoon">
  <meta property="og:title" content="${escape(title)}">
  <meta property="og:description" content="${escape(description)}">
  <meta property="og:url" content="${url}">
  <meta property="og:image" content="${origin}/assets/brand/cocoon-mark.png">
  <meta property="og:image:alt" content="Cocoon logo">
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="${escape(title)}">
  <meta name="twitter:description" content="${escape(description)}">
  <meta name="twitter:image" content="${origin}/assets/brand/cocoon-mark.png">
  <meta name="twitter:image:alt" content="Cocoon logo">
  <script type="application/ld+json">${JSON.stringify({ '@context':'https://schema.org', '@graph':graph }).replaceAll('<', '\\u003c')}</script>
  <!-- /SEO metadata -->`;
}
